<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VSANKAR2" failures="13" tests="13" name="Contest Entry related scenarios" time="2925.999" errors="0" timestamp="19 Mar 2019 05:20:23 GMT">
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_full_reg" time="316.783">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_full_reg(ContestEntryTests.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_full_reg -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_mini_reg" time="346.963">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_mini_reg(ContestEntryTests.java:199)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_mini_reg -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_silver_user" time="292.242">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_silver_user(ContestEntryTests.java:294)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_silver_user -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_social_user" time="360.959">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_social_user(ContestEntryTests.java:392)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_social_user -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_with_tc_v_without_ck" time="149.534">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_with_tc_v_without_ck(ContestEntryTests.java:467)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_with_tc_v_without_ck -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_with_ck_without_tc_v" time="104.724">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_with_ck_without_tc_v(ContestEntryTests.java:528)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_with_ck_without_tc_v -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_with_mulitple_ck" time="108.323">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_with_mulitple_ck(ContestEntryTests.java:583)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_with_mulitple_ck -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_failed_contest_entry" time="268.567">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_failed_contest_entry(ContestEntryTests.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_failed_contest_entry -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_invalid_ck_on_admin_valid_on_url" time="143.122">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_invalid_ck_on_admin_valid_on_url(ContestEntryTests.java:788)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_invalid_ck_on_admin_valid_on_url -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_invalid_ck_on_url_valid_on_admin" time="104.296">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_invalid_ck_on_url_valid_on_admin(ContestEntryTests.java:853)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_invalid_ck_on_url_valid_on_admin -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_invalid_tc_on_url_valid_ck_on_admin" time="111.032">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_invalid_tc_on_url_valid_ck_on_admin(ContestEntryTests.java:899)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_invalid_tc_on_url_valid_ck_on_admin -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_contest_entry_queue" time="249.645">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_contest_entry_queue(ContestEntryTests.java:958)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_contest_entry_queue -->
  <testcase classname="com.contestentry.ContestEntryTests" name="verify_bmh_queue" time="156.613">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.util.WrapperFunctions.assertTrue(WrapperFunctions.java:1708)
	at com.contestentry.ContestEntryTests.verify_bmh_queue(ContestEntryTests.java:1063)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_bmh_queue -->
</testsuite> <!-- Contest Entry related scenarios -->
