<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VSANKAR2" failures="3" tests="10" name="Token Awarding and CategoryMenus related scenarios" time="1713.258" errors="0" timestamp="19 Mar 2019 05:00:10 GMT">
  <testcase classname="com.miscellaneous.SubCategoryMenuTests" name="verify_page_articles_count" time="236.702"/>
  <testcase classname="com.awardtokens.SegIdTokens" name="verify_tokens_seg_id" time="136.105">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at com.util.WrapperFunctions.assertEqualsInt(WrapperFunctions.java:1632)
	at com.awardtokens.SegIdTokens.verify_tokens_seg_id(SegIdTokens.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verify_tokens_seg_id -->
  <testcase classname="com.awardtokens.TokenQueueTests" name="verify_credit_token_queue" time="195.564">
    <failure type="java.lang.AssertionError" message="expected [FRONTPAGE] but found [PCHREWARDS]">
      <![CDATA[java.lang.AssertionError: expected [FRONTPAGE] but found [PCHREWARDS]
	at com.util.WrapperFunctions.assertEquals(WrapperFunctions.java:1580)
	at com.awardtokens.TokenQueueTests.verify_credit_token_queue(TokenQueueTests.java:65)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verify_credit_token_queue -->
  <testcase classname="com.awardtokens.BirthdayTests" name="birthday_tokens" time="225.565">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at com.util.WrapperFunctions.assertEqualsInt(WrapperFunctions.java:1632)
	at com.awardtokens.BirthdayTests.birthday_tokens(BirthdayTests.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- birthday_tokens -->
  <testcase classname="com.miscellaneous.CategoryMenuTests" name="verfiy_newly_added_sub_category" time="104.374"/>
  <testcase classname="com.miscellaneous.SubCategoryMenuTests" name="verify_native_ad_positioning" time="127.181"/>
  <testcase classname="com.miscellaneous.SubCategoryMenuTests" name="verify_ads_on_sub_category_page" time="154.214"/>
  <testcase classname="com.miscellaneous.CategoryMenuTests" name="verify_native_gpt_ad_positioning" time="107.821"/>
  <testcase classname="com.miscellaneous.CategoryMenuTests" name="verify_top_story_native_ad" time="109.158"/>
  <testcase classname="com.miscellaneous.CategoryMenuTests" name="verify_ads_on_category_page" time="161.143"/>
</testsuite> <!-- Token Awarding and CategoryMenus related scenarios -->
