<?xml version="1.0" encoding="UTF-8"?><testsuite errors="0" failures="1" name="Token queue" skipped="0" tests="1" time="504.1" timestamp="2019-08-21 12:27:48"><testcase name="Verify token queue by making the an invalid api details"><failure message="Token queue records are still present in table after run the cron helper url expected:&lt;0&gt; but was:&lt;3&gt;" type="java.lang.AssertionError">Token queue records are still present in table after run the cron helper url expected:&lt;0&gt; but was:&lt;3&gt;</failure><system-err>Token queue records are still present in table after run the cron helper url expected:&lt;0&gt; but was:&lt;3&gt;&#13;
com.pch.automation.stepdefinitions.fp.TokenQueueSteps.verifyAbsenceOfTokenQueueRecord(TokenQueueSteps.java:34)&#13;
</system-err></testcase></testsuite>